const express=require("express");
const bodyParser=require("body-parser");
const ejs=require("ejs");
require("dotenv").config();
const app=express();
const homePage=require("./router/homePage");
const games=require("./router/game");
const notes=require("./router/notes");
const about=require("./router/about");
const tools=require("./router/tools");
const connectDB=require("./db");
connectDB();
app.use(bodyParser.urlencoded({extended: true}));
app.use(express.static("public"));
app.set('view engine','ejs');
app.use("/",homePage);
app.use("/games",games);
app.use("/notes",notes);
app.use("/aboutMe",about);
app.use("/tools",tools);
const PORT=process.env.PORT;
app.listen(PORT,console.log("server started at port:"+PORT));
